#! /bin/sh
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# colors
bspc config normal_border_color   "#073642"
bspc config active_border_color   "#cb4b16"
bspc config focused_border_color  "#2aa198"
bspc config presel_feedback_color "#55268bd2"

#mouse controls floating window
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
